language: c

matrix:
  include:
    - os: linux
      dist: trusty

      script:
        - git clone --depth=1 https://github.com/nim-lang/Nim.git
        - cd Nim
        - sh ci/build.sh
        - export PATH=$PATH:"`pwd`/bin"
        - ./koch tools -d:release
        - nimble install -y
        - cd ..
        - make
